### PR TITLE
Make forward compatible with PHP 8.0

### LINKED ISSUE #7: Make parser PHP 8.0 compatible
I tried to make [masquerade](https://github.com/elgentos/masquerade) PHP 8.0 compatible but ran into the following error;

`PHP Parse error:  syntax error, unexpected token "match" in /data/elgentos/masquerade/vendor/elgentos/parser/src/Parser/Stories/Reader/Complex.php on line 83`

It turns out, `match` (and `Match`) is now a reserved word in PHP 8.0 due to the [match expression RFC](https://wiki.php.net/rfc/match_expression_v2). 

So this class should be renamed; https://github.com/elgentos/parser/blob/master/src/Parser/Rule/Match.php

### PR DESCRIPTION
**Pull request by janmartenjongerius**
Closes #7 

## Match class
The class `Match` cannot be used in PHP 8, because [`match`](https://www.php.net/manual/en/control-structures.match.php) is a new control structure.

- https://www.php.net/manual/en/migration80.incompatible.php

## Next version
I propose tagging the new release to version `3.0.0` because of a backward breaking change in the name of the `Match` class.

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
:heart:

**Comment by peterjaap** [comment]
@JeroenBoersma could you look into this? Also see #7

**Comment by janmartenjongerius** [comment]
@JeroenBoersma I've replaced Travis with GitHub Actions. Can you update the branch rules so it requires GitHub Actions instead of Travis and perform a review of this pull request?

/cc @peterjaap

**Review by JeroenBoersma — APPROVED** [review]
LGTM

**Pull request merged**
